name: Publish Python Package to PyPI

on:
  push:
    branches:
      - master  # Or 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the latest code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Change this to your desired Python version

      # Install dependencies including bump2version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version

      # Set up Git identity
      - name: Configure Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      # Automatically bump the version (e.g., patch, minor, major)
      - name: Bump version and commit
        run: |
          bump2version minor  # Replace 'patch' with 'minor' or 'major' as needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for committing back to the repository

      # Build the package
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      # Publish to PyPI
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
