name: Publish Python Package to PyPI

on:
  push:
    branches:
      - master  # Or 'main', depending on your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the latest code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Change this to your desired Python version

      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # Build the package
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      # Publish to PyPI
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
